<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.5</Version>
    <Authors>moe</Authors>
    <SPTPath Condition="'$(SPTPath)' == ''">$(MSBuildThisFileDirectory)..\..\客户端</SPTPath>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
